import { Lexend } from "next/font/google";
import "./globals.css";
import SignInProvider from "@/Contex/SignIncontex";
import ValidProvider from "@/Contex/Validcontex";

const lexfont = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sign-In-Up",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ValidProvider>
        <SignInProvider>
          <body className={`${lexfont.variable} overflow-hidden  antialiased`}>
            {children}
          </body>
        </SignInProvider>
      </ValidProvider>
    </html>
  );
}
